[package]
name = "vectorlite-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "vectorlite"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
vectorlite = { path = ".." }
